# Generated by Django 5.2 on 2025-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('izin_gunu', models.FloatField(default=15)),
            ],
        ),
    ]
