# Generated by Django 5.1.3 on 2025-04-29 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_personel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzinTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('durum', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi')], default='Beklemede', max_length=20)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.personel')),
            ],
        ),
    ]
